"""add login security fields

Revision ID: 6867621b2082
Revises: b58a5a295c3b
Create Date: 2026-01-09 21:05:04.072532

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6867621b2082'
down_revision = 'b58a5a295c3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_features')
    op.drop_table('features')
    op.alter_column('client_subscriptions', 'plan_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('client_subscriptions_client_id_key'), 'client_subscriptions', type_='unique')
    op.drop_column('client_subscriptions', 'created_at')
    op.add_column('clients', sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
    op.add_column('clients', sa.Column('locked_until', sa.DateTime(), nullable=True))
    op.drop_column('clients', 'updated_at')
    op.drop_column('plans', 'description')
    op.drop_column('plans', 'monthly_price')
    op.drop_column('plans', 'is_active')
    op.drop_column('plans', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('plans', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('plans', sa.Column('monthly_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.add_column('plans', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('clients', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('clients', 'locked_until')
    op.drop_column('clients', 'failed_login_attempts')
    op.add_column('client_subscriptions', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('client_subscriptions_client_id_key'), 'client_subscriptions', ['client_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('client_subscriptions', 'plan_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('features',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('features_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='features_pkey'),
    sa.UniqueConstraint('code', name='features_code_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('plan_features',
    sa.Column('plan_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('feature_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], name=op.f('plan_features_feature_id_fkey')),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('plan_features_plan_id_fkey')),
    sa.PrimaryKeyConstraint('plan_id', 'feature_id', name=op.f('plan_features_pkey'))
    )
    # ### end Alembic commands ###
