"""add_patpass_inscriptions

Revision ID: 8439560cdab6
Revises: 9ff469be13eb
Create Date: 2026-03-30 16:35:00.724800

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8439560cdab6'
down_revision = '9ff469be13eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patpass_inscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('empresa', sa.String(length=255), nullable=True),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('plan_code', sa.String(length=50), nullable=False),
    sa.Column('plan_name', sa.String(length=100), nullable=False),
    sa.Column('buy_order', sa.String(length=100), nullable=False),
    sa.Column('tbk_user', sa.String(length=255), nullable=True),
    sa.Column('amount_clp', sa.Integer(), nullable=False),
    sa.Column('authorization_code', sa.String(length=50), nullable=True),
    sa.Column('card_type', sa.String(length=50), nullable=True),
    sa.Column('card_last_four', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patpass_inscriptions_buy_order'), 'patpass_inscriptions', ['buy_order'], unique=True)
    op.create_index(op.f('ix_patpass_inscriptions_email'), 'patpass_inscriptions', ['email'], unique=False)
    op.drop_table('plan_change_events')
    op.alter_column('aws_accounts', 'external_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=64),
               nullable=False)
    op.create_index(op.f('ix_aws_accounts_external_id'), 'aws_accounts', ['external_id'], unique=False)
    op.drop_index(op.f('idx_findings_client_resolved'), table_name='aws_findings')
    op.drop_index(op.f('idx_findings_resource_client'), table_name='aws_findings')
    op.drop_index(op.f('idx_findings_resource_client_resolved'), table_name='aws_findings')
    op.drop_constraint(op.f('uq_client_resource_type'), 'aws_findings', type_='unique')
    op.alter_column('aws_resource_inventory', 'tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('aws_resource_inventory', 'resource_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('idx_inventory_account_id'), table_name='aws_resource_inventory')
    op.drop_index(op.f('idx_inventory_active'), table_name='aws_resource_inventory')
    op.drop_index(op.f('idx_inventory_client_active'), table_name='aws_resource_inventory')
    op.drop_index(op.f('idx_inventory_client_id'), table_name='aws_resource_inventory')
    op.drop_index(op.f('idx_inventory_client_service'), table_name='aws_resource_inventory', postgresql_where='(is_active = true)')
    op.drop_index(op.f('idx_inventory_resource'), table_name='aws_resource_inventory')
    op.drop_index(op.f('idx_inventory_resource_type'), table_name='aws_resource_inventory')
    op.drop_index(op.f('idx_inventory_service_name'), table_name='aws_resource_inventory')
    op.drop_index(op.f('idx_inventory_type'), table_name='aws_resource_inventory')
    op.drop_constraint(op.f('uq_client_resource'), 'aws_resource_inventory', type_='unique')
    op.create_index(op.f('ix_aws_resource_inventory_resource_id'), 'aws_resource_inventory', ['resource_id'], unique=False)
    op.create_index(op.f('ix_aws_resource_inventory_resource_type'), 'aws_resource_inventory', ['resource_type'], unique=False)
    op.create_index(op.f('ix_aws_resource_inventory_service_name'), 'aws_resource_inventory', ['service_name'], unique=False)
    op.alter_column('clients', 'pais',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_constraint(op.f('mp_subscriptions_mp_subscription_id_key'), 'mp_subscriptions', type_='unique')
    op.drop_index(op.f('ix_mp_subscriptions_mp_subscription_id'), table_name='mp_subscriptions')
    op.create_index(op.f('ix_mp_subscriptions_mp_subscription_id'), 'mp_subscriptions', ['mp_subscription_id'], unique=True)
    op.drop_constraint(op.f('notifications_user_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('payments_paypal_subscription_id_key'), 'payments', type_='unique')
    op.drop_index(op.f('ix_payments_paypal_subscription_id'), table_name='payments')
    op.create_index(op.f('ix_payments_paypal_subscription_id'), 'payments', ['paypal_subscription_id'], unique=True)
    op.alter_column('plan_upgrade_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_risk_snapshot_client_date'), table_name='risk_snapshots')
    op.drop_constraint(op.f('fk_risk_snapshot_client'), 'risk_snapshots', type_='foreignkey')
    op.drop_index(op.f('idx_support_ticket_messages_ticket_id'), table_name='support_ticket_messages')
    op.create_index(op.f('ix_support_ticket_messages_ticket_id'), 'support_ticket_messages', ['ticket_id'], unique=False)
    op.drop_constraint(op.f('support_ticket_messages_ticket_id_fkey'), 'support_ticket_messages', type_='foreignkey')
    op.create_foreign_key(None, 'support_ticket_messages', 'support_tickets', ['ticket_id'], ['id'])
    op.drop_index(op.f('idx_support_tickets_client_id'), table_name='support_tickets')
    op.drop_constraint(op.f('support_tickets_ticket_number_key'), 'support_tickets', type_='unique')
    op.create_index(op.f('ix_support_tickets_client_id'), 'support_tickets', ['client_id'], unique=False)
    op.create_index(op.f('ix_support_tickets_ticket_number'), 'support_tickets', ['ticket_number'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_support_tickets_ticket_number'), table_name='support_tickets')
    op.drop_index(op.f('ix_support_tickets_client_id'), table_name='support_tickets')
    op.create_unique_constraint(op.f('support_tickets_ticket_number_key'), 'support_tickets', ['ticket_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_support_tickets_client_id'), 'support_tickets', ['client_id'], unique=False)
    op.drop_constraint(None, 'support_ticket_messages', type_='foreignkey')
    op.create_foreign_key(op.f('support_ticket_messages_ticket_id_fkey'), 'support_ticket_messages', 'support_tickets', ['ticket_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_support_ticket_messages_ticket_id'), table_name='support_ticket_messages')
    op.create_index(op.f('idx_support_ticket_messages_ticket_id'), 'support_ticket_messages', ['ticket_id'], unique=False)
    op.create_foreign_key(op.f('fk_risk_snapshot_client'), 'risk_snapshots', 'clients', ['client_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_risk_snapshot_client_date'), 'risk_snapshots', ['client_id', 'created_at'], unique=False)
    op.alter_column('plan_upgrade_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_payments_paypal_subscription_id'), table_name='payments')
    op.create_index(op.f('ix_payments_paypal_subscription_id'), 'payments', ['paypal_subscription_id'], unique=False)
    op.create_unique_constraint(op.f('payments_paypal_subscription_id_key'), 'payments', ['paypal_subscription_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_user_id_fkey'), 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_mp_subscriptions_mp_subscription_id'), table_name='mp_subscriptions')
    op.create_index(op.f('ix_mp_subscriptions_mp_subscription_id'), 'mp_subscriptions', ['mp_subscription_id'], unique=False)
    op.create_unique_constraint(op.f('mp_subscriptions_mp_subscription_id_key'), 'mp_subscriptions', ['mp_subscription_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('clients', 'pais',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=25),
               existing_nullable=True)
    op.drop_index(op.f('ix_aws_resource_inventory_service_name'), table_name='aws_resource_inventory')
    op.drop_index(op.f('ix_aws_resource_inventory_resource_type'), table_name='aws_resource_inventory')
    op.drop_index(op.f('ix_aws_resource_inventory_resource_id'), table_name='aws_resource_inventory')
    op.create_unique_constraint(op.f('uq_client_resource'), 'aws_resource_inventory', ['client_id', 'resource_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_inventory_type'), 'aws_resource_inventory', ['client_id', 'resource_type'], unique=False)
    op.create_index(op.f('idx_inventory_service_name'), 'aws_resource_inventory', ['service_name'], unique=False)
    op.create_index(op.f('idx_inventory_resource_type'), 'aws_resource_inventory', ['client_id', 'resource_type'], unique=False)
    op.create_index(op.f('idx_inventory_resource'), 'aws_resource_inventory', ['client_id', 'resource_id'], unique=False)
    op.create_index(op.f('idx_inventory_client_service'), 'aws_resource_inventory', ['client_id', 'service_name'], unique=False, postgresql_where='(is_active = true)')
    op.create_index(op.f('idx_inventory_client_id'), 'aws_resource_inventory', ['client_id'], unique=False)
    op.create_index(op.f('idx_inventory_client_active'), 'aws_resource_inventory', ['client_id', 'is_active'], unique=False)
    op.create_index(op.f('idx_inventory_active'), 'aws_resource_inventory', ['is_active'], unique=False)
    op.create_index(op.f('idx_inventory_account_id'), 'aws_resource_inventory', ['aws_account_id'], unique=False)
    op.alter_column('aws_resource_inventory', 'resource_metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('aws_resource_inventory', 'tags',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_unique_constraint(op.f('uq_client_resource_type'), 'aws_findings', ['client_id', 'resource_id', 'finding_type'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_findings_resource_client_resolved'), 'aws_findings', ['resource_id', 'client_id', 'resolved'], unique=False)
    op.create_index(op.f('idx_findings_resource_client'), 'aws_findings', ['resource_id', 'client_id'], unique=False)
    op.create_index(op.f('idx_findings_client_resolved'), 'aws_findings', ['client_id', 'resolved'], unique=False)
    op.drop_index(op.f('ix_aws_accounts_external_id'), table_name='aws_accounts')
    op.alter_column('aws_accounts', 'external_id',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=255),
               nullable=True)
    op.create_table('plan_change_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('old_plan', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('new_plan', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('changed_by_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], name=op.f('fk_plan_change_user')),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_plan_change_client')),
    sa.PrimaryKeyConstraint('id', name=op.f('plan_change_events_pkey'))
    )
    op.drop_index(op.f('ix_patpass_inscriptions_email'), table_name='patpass_inscriptions')
    op.drop_index(op.f('ix_patpass_inscriptions_buy_order'), table_name='patpass_inscriptions')
    op.drop_table('patpass_inscriptions')
    # ### end Alembic commands ###
