"""reconcile_indexes_constraints

Revision ID: 93bd8e505868
Revises: e4f9a1b7c2d3
Create Date: 2026-07-27 20:47:35.930453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93bd8e505868'
down_revision = 'e4f9a1b7c2d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_findings_client_resolved', 'aws_findings', ['client_id', 'resolved'], unique=False)
    op.create_index('idx_findings_resource_client', 'aws_findings', ['resource_id', 'client_id'], unique=False)
    op.create_index('idx_findings_resource_client_resolved', 'aws_findings', ['resource_id', 'client_id', 'resolved'], unique=False)
    op.create_unique_constraint('uq_client_resource_type', 'aws_findings', ['client_id', 'resource_id', 'finding_type'])
    op.create_index('idx_inventory_client_active', 'aws_resource_inventory', ['client_id', 'is_active'], unique=False)
    op.create_index('idx_inventory_client_id', 'aws_resource_inventory', ['client_id'], unique=False)
    op.create_index('idx_inventory_client_service', 'aws_resource_inventory', ['client_id', 'service_name'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index('idx_inventory_type', 'aws_resource_inventory', ['client_id', 'resource_type'], unique=False)
    op.create_unique_constraint('uq_client_resource', 'aws_resource_inventory', ['client_id', 'resource_id'])
    op.create_index('uq_client_subscription_active', 'client_subscriptions', ['client_id'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_index('idx_risk_snapshot_client_date', 'risk_snapshots', ['client_id', 'created_at'], unique=False)
    op.create_foreign_key('fk_risk_snapshot_client', 'risk_snapshots', 'clients', ['client_id'], ['id'])
    op.create_unique_constraint('uq_client_tag_key', 'tag_policies', ['client_id', 'tag_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_client_tag_key', 'tag_policies', type_='unique')
    op.drop_constraint('fk_risk_snapshot_client', 'risk_snapshots', type_='foreignkey')
    op.drop_index('idx_risk_snapshot_client_date', table_name='risk_snapshots')
    op.drop_index('uq_client_subscription_active', table_name='client_subscriptions', postgresql_where=sa.text('is_active = true'))
    op.drop_constraint('uq_client_resource', 'aws_resource_inventory', type_='unique')
    op.drop_index('idx_inventory_type', table_name='aws_resource_inventory')
    op.drop_index('idx_inventory_client_service', table_name='aws_resource_inventory', postgresql_where=sa.text('is_active = true'))
    op.drop_index('idx_inventory_client_id', table_name='aws_resource_inventory')
    op.drop_index('idx_inventory_client_active', table_name='aws_resource_inventory')
    op.drop_constraint('uq_client_resource_type', 'aws_findings', type_='unique')
    op.drop_index('idx_findings_resource_client_resolved', table_name='aws_findings')
    op.drop_index('idx_findings_resource_client', table_name='aws_findings')
    op.drop_index('idx_findings_client_resolved', table_name='aws_findings')
    # ### end Alembic commands ###
