"""add password expiration

Revision ID: f7e51164c8b9
Revises: 6867621b2082
Create Date: 2026-01-09 21:33:27.172902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7e51164c8b9'
down_revision = '6867621b2082'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
